# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='model_pic',
            field=models.FileField(default=0, upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
