# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='albums/%Y/%m/%d/'),
        ),
    ]
