# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(upload_to='albums'),
        ),
    ]
