# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20170924_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to=b'albums'),
        ),
    ]
